### ISSUE TITLE
关于 目录自动编号

### ISSUE THREAD

**Issue by deepwjp** [Soanguy/typora-theme-autumnus#1]
主题非常好看，但是关于目录自动编号感觉有些多余，因为我们都习惯自己加标号，而且根据每个人不同习惯，标号也会不同，最后再加上自动的标号看着就很奇怪
![自动编号](https://user-images.githubusercontent.com/62140036/96745114-5bece100-13f8-11eb-8f6e-7e32a0652d20.png)

**Comment by Soanguy** [comment]
不想侧边栏自动目录的话，
如果你使用的是 autumnus.css 那么删除大概1126行开始到1186行的

```
/* 大纲目录自动编号 */
.sidebar-content {

......

.outline-h6>.outline-item>.outline-label:before {
	counter-increment: h6;
	content: counter(h3) "."counter(h4) "."counter(h5) "."counter(h6) " ";
}
```

opt-autumnus 的话大概是删除 1080-1135行；
qd-light 的话大概是删除 1030-1083行。

**Comment by deepwjp** [comment]
OK
