### ISSUE TITLE
Opt 系列，高亮（==内容==）的样式出现错误

### ISSUE THREAD

**Issue by CarameowCookie** [Soanguy/typora-theme-autumnus#10]
如题

**Comment by Soanguy** [comment]
可以的话可以贴个图吗。我电脑上是这么显示的
![image](https://user-images.githubusercontent.com/24608949/102443561-07658b00-4062-11eb-93ca-4ffc1e8e162f.png)

**Comment by CarameowCookie** [comment]
![Style](https://user-images.githubusercontent.com/74455347/102450716-063c5a00-4072-11eb-9121-15de6d11b21f.png)

不知什么原因，无法加载你的图片。

**Comment by Soanguy** [comment]
网络吧，github的图片似乎会被屏蔽。
我看了图片，这是正常的。我把它修改成了这个样子。如果你想要还原回上一个版本样式的话，可以加入下面代码：
```
mark {
	margin: 0 5px;
	color: var(--mark-color);
	padding: 1px 4px;
	border-radius: 5px;
	background-color: var(--mark-bg);
}
```
