### ISSUE TITLE
less-light.css样式PDF导出问题

### ISSUE THREAD

**Issue by vagitablebirdcode** [Soanguy/typora-theme-autumnus#12]
1. PDF导出后，几乎所有样式消失。
2. 代码样式导出时出现重影。
3. 代码在导出前没有换行，导出后有换行时，导出样式出问题。

**Comment by Soanguy** [comment]
我之前是为了打印删掉了所有的样式，如果不喜欢的话，我一会在重新整理一下。
关于第三个问题，如果可以的话可以发送一下图片看一下问题是什么吗。

**Comment by Soanguy** [comment]
修改了一下，应该没有问题了。

**Comment by vagitablebirdcode** [comment]
非常感谢你的回复！重影和错行的截图如下：（图1和2是重影问题，图3和4是错行问题）





十分喜欢你的主题，希望你能解决，非常感谢了！








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Autumnus"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 晚上8:13
收件人: "Soanguy/typora-theme-autumnus"<typora-theme-autumnus@noreply.github.com&gt;; 
抄送: "王土"<1826515049@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Soanguy/typora-theme-autumnus] less-light.css样式PDF导出问题 (#12)





 
修改了一下，应该没有问题了。

**Comment by Soanguy** [comment]
好像你并没有添付图片的附件。😂😂😂
