### ISSUE TITLE
qd light 样式，加粗后是不是字体不对？

### ISSUE THREAD

**Issue by wkingnet** [Soanguy/typora-theme-autumnus#13]
应该用的是Noto Sans CJK SC Regular字体吧？加粗以后怎么变的像宋体了

![QQ截图20210130021650](https://user-images.githubusercontent.com/57652989/106312310-69402400-62a1-11eb-9450-9af7592d09a3.png)

![QQ截图20210130021748](https://user-images.githubusercontent.com/57652989/106312318-6a715100-62a1-11eb-9336-3b9b0432c90f.png)

**Comment by Soanguy** [comment]
不是的，我特别的使用了宋体来表示强调。
