### ISSUE TITLE
能否自定义背景图片？？？

### ISSUE THREAD

**Issue by zym787** [Soanguy/typora-theme-autumnus#15]
如题，能否自定义背景图片？？谢谢~~~

**Comment by Soanguy** [comment]
可以，图片背景的话，我只在 fluence 的主题里设定过。在每个 fluence 主题的 css 文件最后都有一段类似下面的代码：

```
:root{
—blur-img:url(一长串代码);
}
```
将括号里的代码替换成你想要替换的图片的本地地址或者网络地址就好了。
