### ISSUE TITLE
好像对字体的斜体和加粗斜体格式上支持有问题

### ISSUE THREAD

**Issue by wazamono** [Soanguy/typora-theme-autumnus#16]
*斜体和 ***加粗斜体的显示好像有问题，切换其他主题好像就没有这个问题了。也已经安装了推荐的字体，显示效果还是一样的，（win10下最新版typora）麻烦作者具体看下截图：
---
其他主题下的显示效果
![typora issue](https://user-images.githubusercontent.com/57340886/109469603-37d99480-7aa9-11eb-9b8a-a2f4156c7e73.jpg)

---
你的主题下的显示效果
![ty](https://user-images.githubusercontent.com/57340886/109469734-648dac00-7aa9-11eb-9fe8-733499e29187.jpg)

**Comment by Soanguy** [comment]
我设定的 **斜体** 是在 **加粗** 基础上添加下划线，所以如果是 **斜体** 再加上 **加粗** 的话就和 **斜体** 是一样的显示的是 加粗并添加下划线。
如果你想要对 区别显示 **斜体** 和 **加粗斜体** 的话，可以更改下划线的样式，在 css 文件的最后的部分添加下面的代码就好：
```
#write strong em，#write em strong {
    border-bottom: 4px double #4d97ff;
}
```
最后的显示效果如下：
![image](https://user-images.githubusercontent.com/24608949/109481466-bd644100-7ab7-11eb-95aa-582b5e8ef825.png)
