### ISSUE TITLE
使用了最新的主题会出现抖动

### ISSUE THREAD

**Issue by towelong** [Soanguy/typora-theme-autumnus#18]
![image](https://user-images.githubusercontent.com/41502558/112831726-f1d31900-90c6-11eb-8064-c7320173a3f6.png)
就是这个位置 鼠标悬浮就会抖动

**Comment by Soanguy** [comment]
已修复

**Comment by towelong** [comment]
> 已修复

好的感谢，另外说一句 你的主题非常好看

**Comment by Soanguy** [comment]
谢谢♪(･ω･)ﾉ
