### ISSUE TITLE
fluent主题在打字机模式下新一行的位置在屏幕底端容易被底栏遮蔽

### ISSUE THREAD

**Issue by Alex-coder251** [Soanguy/typora-theme-autumnus#19]
大佬能把新一行的位置挪到屏幕中间吗😂，新一行的位置在屏幕底端打字的时候总得看屏幕下方还很容易被底栏遮蔽

1. 这是大佬的主题在在打字机模式的展示效果![屏幕截图 2021-04-07 170214](https://user-images.githubusercontent.com/58896036/113840553-60009580-97c3-11eb-9f39-7a1b1a5edbd8.png)

2. 这是其他主题在打字机模式的展示效果![屏幕截图 2021-04-07 170407](https://user-images.githubusercontent.com/58896036/113840560-61ca5900-97c3-11eb-8c15-ea1ca42290eb.png)

**Comment by Soanguy** [comment]
我这两天事情有点多，明天我会修改好在发布新的。如果实在不行，可以先切换到其他主题。抱歉

**Comment by Soanguy** [comment]
已修复。有问题的话请联系我。

**Comment by Alex-coder251** [comment]
感谢大大，问题已经解决了
