### ISSUE TITLE
图片链接挂了

### ISSUE THREAD

**Issue by Theigrams** [Soanguy/typora-theme-autumnus#2]
rt，图片链接失效了

**Comment by Soanguy** [comment]
是指主题介绍（readme）中的图片吗，如果是的话，可能是因为国内网络的问题。

![Screenshot_20201026-013019](https://user-images.githubusercontent.com/24608949/97114330-e2702e00-172a-11eb-969f-47d0951249c6.jpg)

主题里的背景图片的话我转码了，应该不会失效呀🤣🤣🤣

**Comment by Theigrams** [comment]
> 是指主题介绍（readme）中的图片吗，如果是的话，可能是因为国内网络的问题。
> 
> ![Screenshot_20201026-013019](https://user-images.githubusercontent.com/24608949/97114330-e2702e00-172a-11eb-969f-47d0951249c6.jpg)
> 
> 主题里的背景图片的话我转码了，应该不会失效呀🤣🤣🤣

是的，挂着梯子后发现能查看了。
