### ISSUE TITLE
如何去除勾选复选框后的删除线

### ISSUE THREAD

**Issue by EchoGroot** [Soanguy/typora-theme-autumnus#21]
请问如何去除勾选复选框后的删除线？这个功能不太适合我，例如复选框下有代码块，勾选复选框后代码块也出现了删除线。

**Comment by Soanguy** [comment]
在 css 文件内搜索：`text-decoration: line-through;` 之后，删掉改行代码即可。
如果是 autumnus 主题，在 autumnus.css 内搜索，其他的相同。

**Comment by EchoGroot** [comment]
解决了，谢谢！这个主题太好看了，爱不释手
