### ISSUE TITLE
鼠标悬停在文件列表上时，鼠标变成了移动文件位置的样式

### ISSUE THREAD

**Issue by EchoGroot** [Soanguy/typora-theme-autumnus#22]
![image](https://user-images.githubusercontent.com/44628981/115522572-cfe04700-a2be-11eb-8dc5-58086abeb6b1.png)

**Comment by Soanguy** [comment]
在主题 css 文件的末尾添加
```
[draggable] {
  cursor: default;
}
```
就可以改变可拖动文件区域的鼠标样式。更多的鼠标样式可以参考 [CSS cursor 属性](https://www.w3school.com.cn/cssref/pr_class_cursor.asp)。

**Comment by EchoGroot** [comment]
解决了，谢谢大佬
