### ISSUE TITLE
Themes Not Working on Mac

### ISSUE THREAD

**Issue by L-Ryland** [Soanguy/typora-theme-autumnus#23]
When I use less-fluent dark theme, themes is rather bright with the svg file shown as background. 
There is nothing like transparent.

**Comment by Soanguy** [comment]
I not have a Mac ,so I can just test it on Windows. But you can try add the following codes into  `less-light-fluent.css`:

```
#write:before,
#write:after,
ul.dropdown-menu:before,
#typora-sidebar:before,
footer.ty-footer:before,
#typora-quick-open:before,
.modal-content:before {
    -webkit-backdrop-filter: blur(15px);
    backdrop-filter: blur(15px);
}
```
 I'm not sure whether it will work.

**Comment by L-Ryland** [comment]
Thanks for your work and now I find the issue: 
I pasted these codes into the css file and it should be some blur effects, but nothing blurs at all. 
So I looked for some documention on the CSS site and found something: 
<img width="918" alt="Screen Shot 2021-05-26 at 6 02 11 PM" src="https://user-images.githubusercontent.com/41134883/119641690-813d4400-be4c-11eb-803a-bee32a8ba7c3.png">
As you can see blur on a SVG background only works on Firefox. And I guess Typora on mac could based on Safari Webkit!

**Comment by Soanguy** [comment]
I rechecked my code. maybe you can try add the following codes to your `less-light-fluent.css`:
```
#write{
z-index:0;
}
```
I'm trying to make a virtual machine of Mac on my windows pc. After its installing, I'll try again to find the bug.

**Comment by Soanguy** [comment]
I rechecked my code. maybe you can try add the following codes to your `less-light-fluent.css`:
```
#write{
z-index:0;
}
```
I'm trying to make a virtual machine of Mac on my windows pc. After its installing, I'll try again to find the bug.
