### ISSUE TITLE
autumnus主题底部显示不正常

### ISSUE THREAD

**Issue by xzyone** [Soanguy/typora-theme-autumnus#25]
Autumnus主题的底部方块显示不完整：

_这是Autumnus的底部_
![image](https://user-images.githubusercontent.com/23356216/120746454-d3a7f000-c531-11eb-923b-90be99ea6c9b.png)

_这是OPT的底部_
![image](https://user-images.githubusercontent.com/23356216/120746543-04882500-c532-11eb-9920-c56eba255925.png)

**Comment by Soanguy** [comment]
在 `autumnus.css` 的最后一行添加下面的代码就好：
```
@media (min-width: 1100px)
.typora-node #write {
    min-height: 80%;
}

@media (min-width: 1100px)
#write {
    margin:5rem auto;
}
```

**Comment by xzyone** [comment]
> 在 `autumnus.css` 的最后一行添加下面的代码就好：
> 
> ```
> @media (min-width: 1100px)
> .typora-node #write {
>     min-height: 80%;
> }
> 
> @media (min-width: 1100px)
> #write {
>     margin:5rem auto;
> }
> ```

加了，但还是没效果

**Comment by Soanguy** [comment]
呃呃呃，抱歉。忘记加套嵌了。把下面的代码加进去。刚才的那些删掉吧。保存后，重启 Typora 再试试看。
```
@media (min-width: 1100px) {
    .typora-node #write {
        min-height: 80%;
    }
}

@media (min-width: 1100px) {
    #write {
        margin: 5rem auto;
    }
}
```

**Comment by xzyone** [comment]
> 呃呃呃，抱歉。忘记加套嵌了。把下面的代码加进去。刚才的那些删掉吧。保存后，重启 Typora 再试试看。
> 
> ```
> @media (min-width: 1100px) {
>     .typora-node #write {
>         min-height: 80%;
>     }
> }
> 
> @media (min-width: 1100px) {
>     #write {
>         margin: 5rem auto;
>     }
> }
> ```

解决了，谢谢大佬！

**Comment by xzyone** [comment]
另外，字体那个仓库被屏蔽了，下载不了字体

**Comment by Soanguy** [comment]
不用在意那个，直接点
![image](https://user-images.githubusercontent.com/24608949/120756865-62246d80-c542-11eb-8498-6b4166df620e.png)后，点击`下载zip`
就可以下载了。
