### ISSUE TITLE
在mac下无法正常使用

### ISSUE THREAD

**Issue by zero-hugo** [Soanguy/typora-theme-autumnus#27]
1、Autumnus-Qd主题卡顿严重，然后会造成CPU过载。
2、另外几个有图片的主题，干扰了内容显示，没有像示例里那样是模糊态的。能删掉那张图片就好了。

**Comment by Soanguy** [comment]
我手边并没有 mac 电脑，我在虚拟机上运行也没有办法检查出 bug 到底是出现在什么地方，另外 QD 已经好久没有更新了，或许你可以尝试其他的非模糊主题（我在虚拟机上运行，可能是性能原因，他没有办法运算高斯模糊）。
