### ISSUE TITLE
黑色主题下 ，关于下拉滚动条的颜色

### ISSUE THREAD

**Issue by qidanei624** [Soanguy/typora-theme-autumnus#28]
在黑色主题下， 例如 adark 下拉滚动条颜色能否改成像 adfluent一样容易辨认，看不清哈~
这几个样式我都喜欢， 谢谢分享！！

**Comment by Soanguy** [comment]
1. 颜色的值可以参考该[网站](http://zhongguose.com/)，选择自己喜欢的颜色后，复制代码到下面的相对应位置后。
2. 将修改好的颜色代码复制到想要修改的主题 css 文件最后一行即可。
```
::-webkit-scrollbar {
    background-color: 滚动条的背景色。此处修改成自己喜欢的颜色;
}

::-webkit-scrollbar-thumb {
    background: 滚动条本身的颜色。此处修改成自己喜欢的颜色;
}
```
