### ISSUE TITLE
关于typora绘制mermaid流程图，暗黑模式下连接线为灰色，极不清晰，建议改善显示效果

### ISSUE THREAD

**Issue by Eliasinworld** [Soanguy/typora-theme-autumnus#29]
adark暗黑模式下，采用mermaid绘制typora流程图，流程图的连接线默认为灰色，与青灰色背景相似，不易辨别。

**Comment by Eliasinworld** [comment]
我看了下主题修改设置，但是限于相关知识了解不够，我想请问下关于这种连接线的颜色应该修改哪里的设置，或是本主题是否支持修改连接线的颜色呢？

**Comment by Soanguy** [comment]
感谢反馈，这个是 mermaid 默认的设定，我没有怎么使用 mermaid ，所以没有对他进行大量的修改。你可以试着修改下面 `stroke` 的颜色值看一下有没有用处。然后把这段代码复制粘贴到相对应的主题 css 文件的最后一行。
```
#mermaidChart0 .edgePath .path {
    stroke: #b5d6fc;
    stroke-width: 1.5px;
}
```

**Comment by Eliasinworld** [comment]
> 感谢反馈，这个是 mermaid 默认的设定，我没有怎么使用 mermaid ，所以没有对他进行大量的修改。你可以试着修改下面 `stroke` 的颜色值看一下有没有用处。然后把这段代码复制粘贴到相对应的主题 css 文件的最后一行。
> 
> ```
> #mermaidChart0 .edgePath .path {
>     stroke: #b5d6fc;
>     stroke-width: 1.5px;
> }
> ```

感谢回复，但是尝试修改后仍无效。

**Comment by Soanguy** [comment]
可能是因为原样式的权重太高了，你试着在颜色的后面添加 `!important` 这句话试试。比如像这个样子：
```
#mermaidChart0 .edgePath .path {
    stroke: #b5d6fc !important;
    stroke-width: 1.5px;
}
```

把这些代码粘贴到 `less-dark.css`或者`adark.css`之类的的想要修改的主题文件的最后一行。保存后，重启typora试一下。

**Comment by Soanguy** [comment]
请试着把下面的代码（）粘贴到相对应的主题文件的最后一行，重启typora再试一次：
```
.edgePath .path {
    stroke: var(--theme-color) !important;
    stroke-width: 1.5px;
}
.arrowheadPath {
    fill: var(--theme-color) !important;
}
```

**Comment by Eliasinworld** [comment]
加入！important声明重要性之后生效，但是连接线的箭头依然是灰色的，请问应该设置什么来同时修改箭头的颜色呢

**Comment by Soanguy** [comment]
我刚刚写的那一串就可以线段和箭头一起修改颜色了。你再试一下我刚发的那个。

**Comment by Eliasinworld** [comment]
> 请试着把下面的代码（）粘贴到相对应的主题文件的最后一行，重启typora再试一次：
> 
> ```
> .edgePath .path {
>     stroke: var(--theme-color) !important;
>     stroke-width: 1.5px;
> }
> .arrowheadPath {
>     fill: var(--theme-color) !important;
> }
> ```

感谢，已经生效。而且和主题色相匹配，优秀！
