### ISSUE TITLE
[Feature]悬停于 HTML 元素时的颜色

### ISSUE THREAD

**Issue by Higurashi-kagome** [Soanguy/typora-theme-autumnus#3]
一个很好的主题，感谢作者！⭐️

发现一个完善点：

<details>

<summary><strong>重现</strong></summary>

1. 进入 Typora，在编辑器中输入：

    ```html
    <p align = "center">测试文本</p>
    ```

2. 切换主题为 Autumnus Dark，

3. 将鼠标悬停于输入的文本之上或者点击文本

这时候会发现背景色和文本颜色很接近（都为浅色），导致文本看不清。
</details>

<details>
<summary><strong>Gif</strong></summary>

  ![gif](https://user-images.githubusercontent.com/51501079/100406389-a40abd80-30a0-11eb-9138-1b65a1aac3fe.gif)

</details>

**Comment by Soanguy** [comment]
感谢提出的问题，如果急着使用的话，可以在主题 css 文件的第二行插入下面的代码：
```
.md-rawblock-control:not(.md-rawblock-tooltip) {
    background: #9b9b9b1f;
}
:root {
    --rawblock-edit-panel-bd: #9b9b9b1f;
}
```

如果不急得话，后面我会在修改，然后在发布新的。

**Comment by Higurashi-kagome** [comment]
好的，谢谢！ @Soanguy
