### ISSUE TITLE
问题：alfluent插入表格，卡死

### ISSUE THREAD

**Issue by Yangly0** [Soanguy/typora-theme-autumnus#31]
当我插入表格时候，会自动卡死。

![image](https://user-images.githubusercontent.com/43691492/154513957-17231465-86be-40ec-899e-c25d11eb15db.png)

**Comment by Yangly0** [comment]
问题解决了，其他都没反应，按回车就ok了

**Comment by Soanguy** [comment]
```
.modal-backdrop{
    position: initial;
}
```

把上面的代码添加到 `assets-less` ➡️ `less.css` 这个文件的最后一行，然后重启软件试试看。

**Comment by Yangly0** [comment]
> 

感谢已经可以了
