### ISSUE TITLE
内容目录

### ISSUE THREAD

**Issue by CGQZtoast** [Soanguy/typora-theme-autumnus#32]
插入内容目录显示有点奇怪

**Comment by Soanguy** [comment]
可以描述的更加详细一点吗

**Comment by CGQZtoast** [comment]
![image](https://user-images.githubusercontent.com/82515188/160226771-30e88b2f-a5f3-4ddb-a722-1a72fa6febff.png)

**Comment by CGQZtoast** [comment]
这个样子

**Comment by Soanguy** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/24608949/160227188-42546227-6734-46a8-81db-f9b45d33aa00.png">

<img width="693" alt="image" src="https://user-images.githubusercontent.com/24608949/160227157-5f256a79-8872-4583-83a7-74d7b354af23.png">

预先设定的时候，是依照标题逐级显示的。这不是显示问题。

**Comment by CGQZtoast** [comment]
哦哦 好嘞
