### ISSUE TITLE
导出html样式问题

### ISSUE THREAD

**Issue by steven-sun** [Soanguy/typora-theme-autumnus#33]
非常感谢作者的主题，非常棒！
我用less-light-fluent主题导出html文件时遇到以下问题：
1、毛玻璃效果没显示
2、背景文件不显示
手工添加background-image定义的选择选择器可以显示，但内容滚动露出的部分会被遮挡，和typora中效果不一样，不知是否和第1个问题有关

**Comment by Soanguy** [comment]
1. 毛玻璃效果是因为导出的时候，typora 并不会连同背景图一起导出。需要将背景图和 html 文件放在同一个文件夹下来会被显示。（我在mac系统上导出发现了一些问题。typora 在导出的时候会改变 标签的 class 值。可能就导致了无法正常的使用毛玻璃效果。）

2.滚动部分会被遮挡可以贴图给我看一下吗？

如果你希望在导出的时候不考虑图片的位置，可以选择将图片转换为 base64 。方法如下：

1. 在 `assets-less` 文件夹下的 `fluence.css` 文件的末尾添加如下代码：

```
:root{
   --html-bg:url(“ ”);
}

content,
.on-focus-mode content,
#typora-sidebar,
body.typora-export {
    background-image: var(--html-bg);
}

#write:before,
#write:after,
ul.dropdown-menu:before,
#typora-sidebar:before,
footer.ty-footer:before,
#typora-quick-open:before,
.modal-content:before {
  filter: blur(15px);
}

#write{
  z-index:1;
}
```

2. 将自己想要的背景在👉[转换为base64](https://tool.jisuapi.com/pic2base64.html) 这个网址内转换自己的图片。并复制其代码，如下：
<img width="544" alt="image" src="https://user-images.githubusercontent.com/24608949/160225647-2654d0fe-7510-4ce9-ac63-a55fd3317db4.png”>

3. 将复制的代码粘贴到上面的代码【:root{ --html-bg:url(“ ”);}】引号之内。保存后，重新导出试一下。
（如下图：）
<img width="420" alt="image" src="https://user-images.githubusercontent.com/24608949/160225670-f69ed348-4dc7-4079-bb20-c4b56e9954e2.png”>
