### ISSUE TITLE
Print 主题的正文字体为黑体（而非宋体）

### ISSUE THREAD

**Issue by CarameowCookie** [Soanguy/typora-theme-autumnus#34]
![image](https://user-images.githubusercontent.com/74455347/175912908-8dcc4078-57e7-4d43-8f7a-4fd36d507ba5.png)

**Comment by CarameowCookie** [comment]
有序/无序列表中的字体正常（为宋体），正文字体不正常（为黑体），如图所示。
![image](https://user-images.githubusercontent.com/74455347/175914296-43808024-a245-4320-929a-e7a2030f253a.png)

**Comment by Soanguy** [comment]
新增下面的代码在 less-print.css 的最下方试试：
```
html, body, content, #write{
font-family: var(--text-font-cn);
}
```

**Comment by CarameowCookie** [comment]
> 新增下面的代码在 less-print.css 的最下方试试：
> 
> ```
> html, body, content, #write{
> font-family: var(--text-font-cn);
> }
> ```

起作用了，谢谢！
