### ISSUE TITLE
能否修改Alfluent的背景图片透明度?

### ISSUE THREAD

**Issue by yunzinan** [Soanguy/typora-theme-autumnus#35]
如题😜

**Comment by Soanguy** [comment]
你想要修改的是他的模糊程度吧。在 `snippet` 文件夹下有一个 `fluent.css` 的文件，修改这行代码（第60行到61行）就可以调整模糊度。数值越大越模糊。

```
 backdrop-filter: blur(15px);
 -webkit-backdrop-filter: blur(15px);
```

如果你想要调整模糊的颜色（目前是透明），可以修改这行代码（第85行）中的颜色代码：

```
background-color: #ffffff80;
```

比如把 `#ffffff80` 调整为 `hsla(0, 100%, 75%, 0.3)` 。可以自行选择合适的颜色和透明程度。

修改完成后，可以重启软件试一下效果。或者开启调试模式也可以快速调整。

**Comment by yunzinan** [comment]
感谢!
