### ISSUE TITLE
侧边栏item右击菜单

### ISSUE THREAD

**Issue by S-Explorer** [Soanguy/typora-theme-autumnus#36]
## 多种主题下的侧边栏右击菜单问题

 - 对于 ** 普通 ** 系列主题无bug。
 - 对于 ** XX fluent ** 系列主题侧边右击菜单在侧边栏底层，被侧边栏覆盖。
 - 对于 ** opt Dark ** 主题侧边栏右击菜单闪退。

**Comment by Soanguy** [comment]
把 snippet 文件夹下的 fluent.css 文件的第一行到第三行的 content{ z-index: -1;} 删掉就可以了；

但是这一行代码是  macos 下能够显示高斯模糊的必要代码。windows 系统直接删掉就可以了。

opt dark 会闪退这个问题，我在我的系统上没有发现。可以的话，你可以截个图。或者告诉我你的系统版本和typora 的版本。
