### ISSUE TITLE
太香了

### ISSUE THREAD

**Issue by PowerDi** [Soanguy/typora-theme-autumnus#37]
主题好看极了 不要放弃更新呀！

**Comment by Soanguy** [comment]
如果有什么好的建议可以提呀，可以到时候在更新。主要我目前都是在用 vscode 上的。所以就不怎么更新了

**Comment by PowerDi** [comment]
已经换用vscode来管理笔记了吗
还是同步问题让我犹豫


------------------ 原始邮件 ------------------
发件人: Soanguy ***@***.***&gt;
发送时间: 2022年11月3日 21:26
收件人: Soanguy/typora-theme-autumnus ***@***.***&gt;
抄送: PowerDi ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Soanguy/typora-theme-autumnus] 太香了 (Issue #37)





 
如果有什么好的建议可以提呀，可以到时候在更新。主要我目前都是在用 vscode 上的。所以就不怎么更新了

**Comment by Soanguy** [comment]
mpe 这个插件功能更丰富一些，还可以控制 pdf 的特殊内容的生成，所以就换成那个插件了。typora 虽然也可以，但因为typora 正式版之后才支持一些特殊功能。我在之前就换了，也就没有再去仔细的读他的说明文档了。
同步的话，用坚果云或者 icloud 都ok的。我平时都是直接用 icloud 同步。
