### ISSUE TITLE
Bug报告

### ISSUE THREAD

**Issue by poorjackman** [Soanguy/typora-theme-autumnus#38]
![image](https://user-images.githubusercontent.com/59805382/200101447-123a85b3-d674-48d1-bbfc-a4db1fd0da1f.png)

在win11 typora 1.4.8上测试。

**Comment by Soanguy** [comment]
我在 Windows 上测试并没有发现这个问题，或者是因为主题的版本过低。你可以试着更新最新的版本。
![image](https://user-images.githubusercontent.com/24608949/200815110-3933d2d8-b996-44af-a4d3-b25bc98bdf44.png)

**Comment by Soanguy** [comment]
对不起，我知道问题在哪里了。因为Windows和Mac使用的是不同浏览器内核。这个主题在Mac 上不会有问题。但是在Windows需要删除位于 `snippet` 文件夹下的  `fluent.css` 中的第一行到 第三行。也就是这段代码删除就可以了：
```
 content{
    z-index: -1;
} 
```

**Comment by poorjackman** [comment]
感谢您对开源的无私贡献，您的的作品是我所使用的Typora的主题中，最为精美者，一点问题，瑕不掩瑜。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月9日 19:15
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Soanguy/typora-theme-autumnus] Bug报告 (Issue #38)


对不起，我知道问题在哪里了。因为Windows和Mac使用的是不同浏览器内核。这个主题在Mac 上不会有问题。但是在Windows需要删除位于 snippet 文件夹下的 fluent.css 中的第一行到 第三行。也就是这段代码删除就可以了：

 content{



    z-index: -1;



}



―

**Comment by Soanguy** [comment]
谢谢您的赞美。如果在以后的使用中有什么好的想法或者建议欢迎随时@我。
