### ISSUE TITLE
在侧边栏文件,大纲区域右键菜单被遮挡

### ISSUE THREAD

**Issue by ok-kai** [Soanguy/typora-theme-autumnus#39]
![image](https://user-images.githubusercontent.com/56720916/200164491-47b411e7-2f7f-447b-b7a9-61633fefec7e.png)

**Comment by Index-Out-Of-Range** [comment]
碰到了同样的问题，最新版本typora，win11；fluent类型的主题都会出这个问题

**Comment by Index-Out-Of-Range** [comment]
mac没问题，win有问题

**Comment by Soanguy** [comment]
或者试着更新最新的主题版本试试。我在电脑上没有发现这个问题。
![image](https://user-images.githubusercontent.com/24608949/200815337-5259df1f-3570-4f8d-ac3a-727bd6ff9e2a.png)

**Comment by Soanguy** [comment]
对不起，我知道问题在哪里了。因为Windows和Mac使用的是不同浏览器内核。这个主题在Mac 上不会有问题。但是在Windows需要删除位于 `snippet` 文件夹下的  `fluent.css` 中的第一行到 第三行。也就是这段代码删除就可以了：
```
 content{
    z-index: -1;
} 
```

**Comment by Soanguy** [comment]
对不起，我知道问题在哪里了。因为Windows和Mac使用的是不同浏览器内核。这个主题在Mac 上不会有问题。但是在Windows需要删除位于 `snippet` 文件夹下的  `fluent.css` 中的第一行到 第三行。也就是这段代码删除就可以了：
```
content{
    z-index: -1;
}
```

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月7日 1:21
收件人: ***@***.***>
抄送: ***@***.***>
主题: Re: [Soanguy/typora-theme-autumnus] 在侧边栏文件,大纲区域右键菜单被遮挡 (Issue #39)


碰到了同样的问题，最新版本typora，win11；fluent类型的主题都会出这个问题

―

**Comment by ok-kai** [comment]
非常感谢！😘😘，问题以解决。您的这个主题真的非常漂亮。希望未来不要停止更新！🤑

Soanguy ***@***.***> 于2022年11月9日周三 19:17写道：

**Comment by Soanguy** [comment]
有任何需要改进提高的地方可以@我，我会尽力更新的。
