### ISSUE TITLE
less主题中列表未和常规文本对齐

### ISSUE THREAD

**Issue by CoreJa** [Soanguy/typora-theme-autumnus#7]
![image](https://user-images.githubusercontent.com/28624864/101753440-94ae5a00-3b0d-11eb-9f9f-cfc924dc7a6b.png)

如图，直觉上会希望列表序列与常规文本对齐，另外在引用字段里，列表也产生了奇怪的偏移。

**Comment by Soanguy** [comment]
我在我的电脑上是正常的，可以的话可以贴出你的电脑系统版本、typora的版本吗？
![image](https://user-images.githubusercontent.com/24608949/101794774-2cc63680-3b42-11eb-8d37-67a52784f6eb.png)

**Comment by CoreJa** [comment]
typora版本`0.9.96-1`
OS:`manjaro-kde`

**Comment by CoreJa** [comment]
目前猜测可能是`.less`文件并未被读取，不知`dark.css`是否依赖其他文件，我试试把整个文件夹都放进去

**Comment by CoreJa** [comment]
全部放进去了，但并没有作用，值得一提的是其他主题没问题，例如`autumn-dark`
![image](https://user-images.githubusercontent.com/28624864/101851700-0383c580-3b97-11eb-9b2e-1a293a9b9078.png)

**Comment by Soanguy** [comment]
我知道了，我开启了首行缩进，所以一直没发现这个问题。列表距离边缘太近了。
如果不急用的话，你可以先在 偏好设置 -》 markdown 里面 开启首行缩进。
我会再修改发布新的。

**Comment by Soanguy** [comment]
现在应该可以了。下载最新的试一下。

**Comment by CoreJa** [comment]
ok，更新后使用很丝滑。
