### ISSUE TITLE
Opt 系列，上下角标（^内容^、~内容~）与正常字符之间的间隔过大

### ISSUE THREAD

**Issue by CarameowCookie** [Soanguy/typora-theme-autumnus#8]
希望不留间隔，这样便于有时不通过 TeX 公式而直接输入一些较为简单的带角标的内容

**Comment by Soanguy** [comment]
找到以下代码，删掉即可。
```
.md-meta.md-before, .md-meta.md-after {
padding-left: 0.2rem; 
padding-right: 0.2rem;
}
```

**Comment by CarameowCookie** [comment]
> 找到以下代码，删掉即可。
> 
> ```
> .md-meta.md-before, .md-meta.md-after {
> padding-left: 0.2rem; 
> padding-right: 0.2rem;
> }
> ```

谢谢~
