### ISSUE TITLE
Autumuns Fluence出现Bug

### ISSUE THREAD

**Issue by Aymetic** [Soanguy/typora-theme-autumnus#9]
![image](https://user-images.githubusercontent.com/49681574/102299545-15e27280-3f8e-11eb-8ca2-43ee4deb733d.png)
设置此主题后，打开设置，编辑界面会把设置挡住，无法进行设置，除非切换主题

**Comment by Aymetic** [comment]
Typora 0.9.98Beta
Windows 20H2

**Comment by Soanguy** [comment]
已修复，可以下最新的看一下。

**Comment by Aymetic** [comment]
已修复，谢谢啦
